name = 'cloudflare-tvdb-proxy'
compatibility_date = "2023-12-01"
# pages_build_output_dir = "pages" 
main = "src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
MODE = "debug"

[env.dev.vars]
MODE = "debug"

[env.production]
name = "cloudflare-tvdb-proxy"

[env.production.vars]
MODE = "production"

[env.staging]
name = "cloudflare-tvdb-proxy-staging"

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""

[observability]
[observability.logs]
enabled = false
invocation_logs = true